sudo: required

env:
  - DOCKER_COMPOSE_VERSION=1.20.1

language: java
jdk:
  - oraclejdk8
python:
  - "3.6"
cache:
  directories:
    - "$HOME/.m2/repository"
install:
  - bash install.sh
before_install:
  - sudo apt-get -y install python3-pip python-dev
after_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose build
script:
  - bash test.sh
notifications:
  email: false