language: java
jdk:
  - oraclejdk8
python:
  - "3.6"
cache:
  directories:
    - "$HOME/.m2/repository"
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install requests
before_script:
  - bash install.sh
script:
  - bash test.sh
notifications:
  email: false