version: '3.2'

services:
  blablamove:
    build: ./backend
    image: blablamove
    container_name: blablamove
    depends_on:
      - "queue"
      - "insurance"
      - "point_pricing"
      - "route_finder"
      - "database"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    stdin_open: true
  insurance:
    build: ./external/Insurance
    image: insurance
    container_name: insurance
    expose:
      - "5000"
    ports:
      - "5000:5000"
    stdin_open: true
  point_pricing:
    build: ./external/PointPricing
    image: point_pricing
    container_name: point_pricing
    expose:
      - "5001"
    ports:
      - "5001:5000"
    stdin_open: true
  route_finder:
    build: ./external/RouteFinder
    image: route_finder
    container_name: route_finder
    expose:
      - "5002"
    ports:
      - "5002:5000"
    stdin_open: true
  queue:
    image: rabbitmq
    hostname: main_queue
    container_name: queue
    expose:
      - "5672"
    ports:
      - "5672:5672"
  chaos_monkey:
    build: ./chaos_monkey
    image: chaos_monkey
    container_name: chaos_monkey
    expose:
      - "5008"
    ports:
      - "5008:5008"
    stdin_open: true
    depends_on:
      - "queue"
  database:
    image: 1000kit/h2
    stdin_open: true
    expose:
      - "8082"
    ports:
      - "8082:8082"